services:
  - type: web
    name: ipj_discord_bot
    env: node
    branch: main
    buildCommand: cd bot && npm install
    startCommand: cd bot && npm start
    autoDeploy: true
    envVars:
      - key: BOT_TOKEN
      - key: SITE_URL
      - key: PORT
      - key: VERIFY_SECRET
